### ISSUE TITLE
Image not showinng up

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [VesperAkshay/qr-code-generator#10]
The image is not properly showing up because  it is not linked properly .
Please assign the issue to me.
![image](https://github.com/user-attachments/assets/e7a438ff-5df3-4dc9-9d3f-a366c5277625)

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution.

**Comment by Vaibhav-Kumar-K-R** [comment]
I have linked pull request with reference id #31 .
Please review the changes made.
