### ISSUE TITLE
[FEATURE] Add GitHub Action that automatically displays all contributors in the READM

### ISSUE THREAD

**Issue by shubhagarwal1** [VesperAkshay/qr-code-generator#100]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @VesperAkshay please assign this task to me with level tag

**Comment by VesperAkshay** [comment]
We have a similar issue for this @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> We have a similar issue for this @shubhagarwal1

can work on adding auto labels to new raised issues and PR @VesperAkshay
