### ISSUE TITLE
[FEATURE] Adding custom cursor for the site. 

### ISSUE THREAD

**Issue by userAdityaa** [VesperAkshay/qr-code-generator#101]
## Description
The current cursor pointer does not provide enough visual feedback to users, which may lead to a less engaging experience. A custom cursor pointer can enhance usability and improve overall interaction on the site.

## Proposed Change
- Custom Cursor Design: Create a visually appealing cursor design that aligns with the website's branding and enhances user interaction.
- Cursor States: Implement different cursor states (e.g., hover, click) to provide feedback based on user actions.
- Compatibility: Ensure the custom cursor works across all major browsers and devices for consistent user experience.

## Benefits
- Improved visual feedback for users, making the interface more intuitive.
- Enhanced brand identity through custom design.
- Increased engagement as users feel more connected to the interface.

## Screenshots
![pngimg com - cursor_PNG46](https://github.com/user-attachments/assets/fab9d468-b104-47b9-a6ed-49b8b629cd11)

**Comment by VesperAkshay** [comment]
@userAdityaa I will assign the issue to you
