### ISSUE TITLE
[ENHANCEMENT] Footer social media icons can be improved

### ISSUE THREAD

**Issue by sriraghavi22** [VesperAkshay/qr-code-generator#103]
**Feature description:**
Adding hover effect for social media icons can improve UI

**Use case:**
To make it visually appealing and better user experience

**Proposed solution:**
Can add different types of hover effects to it

**Additional context:**
I would like to work on this

**Comment by VesperAkshay** [comment]
@sriraghavi22 There is already been changes in this 
Please find another issues people are spamming this issue
