### ISSUE TITLE
Sign Out Unverified Users After Registration

### ISSUE THREAD

**Issue by VaibhavKatariya** [VesperAkshay/qr-code-generator#108]
**Description of the issue:**
While working on issue #99, I found that users are kept logged in after registration via email and password, even if they have not verified their email. This can lead to confusion as they have access to features intended for verified users. 

**Steps to reproduce:**

1. Register a new user via email and password.
2. Observe that the user remains logged in and can access features meant for authenticated users.
3. Check access to profile pages and other features.

**Expected result:**
Users should be signed out after registration until they verify their email, when they registered via email/password

**Actual result:**
Users remain logged in and can access **features and links in navbar** that should only be available to verified users. Unverified users can access profile pages and other features, but they cannot access the dashboard.

**Additional information:**
Implementing logic to sign out users after sending a verification email will help prevent access to unverified features. A notification should be displayed to inform users they must verify their email to log in again.

@VesperAkshay let me know what do you think about this. Also assign me this issue and add the necessary labels.

Thanks!

**Comment by VesperAkshay** [comment]
@VaibhavKatariya Assigned the issue
