### ISSUE TITLE
Easy navigation by adding history of your generated qr details on profile page

### ISSUE THREAD

**Issue by eshalshaikh07** [VesperAkshay/qr-code-generator#114]
adding History button and showing list of qr generated by that user

**Use case:**
Easy understanding and access for user at a single location to analyze

**Proposed solution:**
A simple button which in backend linked to database and retrieves the data of qr generated by user.

**Additional context:**
Any other relevant context or screenshots.

**Comment by VesperAkshay** [comment]
Using firebase the database does not store the data of qr code generated so this is not necessary
Additionally you can;t open multiple issue at one time
