### ISSUE TITLE
Update the sign up page

### ISSUE THREAD

**Issue by sakshamsaraf23** [VesperAkshay/qr-code-generator#116]
The sign up page should contain a column where it ask's the name of the user and it should contain two passwords blocks one to set password and one to comfirm it. Additionally we can also add a feature  of going to sign up page from the login page and vise versa . So u want the changes u can assign it to me under the labels of gssoc-ext and hacktoberfest so i can raise my pr.

**Comment by VesperAkshay** [comment]
Already we have a similar issue @sakshamsaraf23
