### ISSUE TITLE
Add contributors in Readme.md

### ISSUE THREAD

**Issue by sakshamsaraf23** [VesperAkshay/qr-code-generator#117]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared
![373815323-76171289-5b05-48c4-a5be-dc8ac76d70cb](https://github.com/user-attachments/assets/87e1585f-3bc6-4af8-9e49-2ede8bdddb5a)
Assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR and I will add this type of Live Contributor Profile Photos in it

**Comment by VesperAkshay** [comment]
we already have a similar issue going on @sakshamsaraf23
