### ISSUE TITLE
Add a .env-example file

### ISSUE THREAD

**Issue by shubhanshu-02** [VesperAkshay/qr-code-generator#118]
I cloned the repository to test it but faced issues due to missing environment variables; could we add an `env-example` file to help new users quickly set up their environment by showing the required variables and their formats? Thanks!

**Comment by VesperAkshay** [comment]
The .env in the repo has already a template 
There is no need for env example

**Comment by shubhanshu-02** [comment]
Oh, I just noticed the template in the .env file. Maybe we should add a note about it in the contributing.md to help new users find it easily?
