### ISSUE TITLE
HOME PAGE ENHANCEMENT

### ISSUE THREAD

**Issue by itsbhh** [VesperAkshay/qr-code-generator#12]
Could you please assign this issue to me under GSSOC'24 extd and Hacktoberfest? I would like to work on making the home page more user-friendly. Thanks!

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution.

**Comment by bhaviya18** [comment]
can you please assign this issue to me @itsbhh to make the UI more attractive
