### ISSUE TITLE
[FEATURE] Adding Hover Effect and animation to social icons

### ISSUE THREAD

**Issue by PATILYASHH** [VesperAkshay/qr-code-generator#120]
**Feature description:**

the social icons are normal and simple adding there a hover effect and some animations 

![image](https://github.com/user-attachments/assets/0d3a1fa9-05bd-4805-90bf-846946d5bc11)

**Comment by PATILYASHH** [comment]
please assign me for this issue

**Comment by bj-jiwrajka** [comment]
@VesperAkshay you can assign it to me. I'll make the PR by tonight

**Comment by itsadi-24** [comment]
@VesperAkshay can you assign it to me?I have done this before and It will take only 1 - 2 hrs to make PR for me

**Comment by bj-jiwrajka** [comment]
> @VesperAkshay can you assign it to me?I have done this before and It will take only 1 - 2 hrs to make PR for me

Actually it's a 5-10 minutes task, shouldn't take more than that

**Comment by itsadi-24** [comment]
> > @VesperAkshay can you assign it to me?I have done this before and It will take only 1 - 2 hrs to make PR for me
> 
> Actually it's a 5-10 minutes task, shouldn't take more than that

Yes,i meant to say within 1-2hr as i was working on something else at that time :)

**Comment by VesperAkshay** [comment]
I am closing this issue as it is not relevant anymore as lots of contributor are spamming this issue
