### ISSUE TITLE
Implement Auto Labeling for Issues and PRs 

### ISSUE THREAD

**Issue by shubhagarwal1** [VesperAkshay/qr-code-generator#123]
I propose to  introduces a GitHub Actions workflow to automatically label issues and pull requests based on specific keywords found in their titles or descriptions. The action checks for keywords such as "bug," "feature," "enhancement," and more, and applies the relevant labels accordingly. 

I have tested the code with raising some issues locally, this works perfectly fine as labels are assigned to them accordingly

![Screenshot 2024-10-04 at 2 07 00 PM](https://github.com/user-attachments/assets/0fe54cb2-aa05-4131-8344-665376cd0534)

**Key features:**
- Uses GitHub Actions to automate the labeling process.
- Matches keywords against predefined labels to streamline categorization.
- Enhances workflow efficiency, particularly for open-source contributions.

This implementation will improve issue and PR management, especially during events like Hacktoberfest.

**Comment by VesperAkshay** [comment]
We already have a issue
