### ISSUE TITLE
[Feature]: Add "Already have an account?" on the Register Page.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [VesperAkshay/qr-code-generator#128]
**Problem Statement**
The Register page currently lacks a user-friendly way for users to navigate to the Login page if they already have an account. This could create confusion and inconvenience for users who are returning but mistakenly land on the Register page.

**Proposed Solution**
Add a text link at the bottom of the registration form that says, "Already have an account? Login here." The text should be clearly visible, styled to match the overall theme, and the "Login here" part should be a clickable link that redirects the user to the Login page.

**Alternatives Considered**
An alternative solution could be displaying a pop-up asking users if they already have an account upon landing on the Register page, but this might disrupt the user experience more than a simple link.

**Additional context**
The addition of this feature will improve user navigation and reduce friction for returning users. It can be placed right below the "Sign Up" button to ensure easy access.

**Comment by VesperAkshay** [comment]
@AbhijitMotekar99 Only one pr at a time
