### ISSUE TITLE
Theme change effect is not proper in login and register page

### ISSUE THREAD

**Issue by LNischala** [VesperAkshay/qr-code-generator#131]
The theme change in the login and register page does not match the color palette of the remaining pages, especially the background color of the body in dark mode. I want to adjust this.@VesperAkshay do approve
![QR img1](https://github.com/user-attachments/assets/e2f00ee9-d4b0-4b22-b14a-e3965221dd98)
![QR img2](https://github.com/user-attachments/assets/35a035f5-19b9-49bc-a7b4-77b73dc0c20c)

**Comment by VesperAkshay** [comment]
@LNischala We already have a similar issue
