### ISSUE TITLE
[Bug]: [display error message for invalid email format]

### ISSUE THREAD

**Issue by bj-jiwrajka** [VesperAkshay/qr-code-generator#136]
**Description**
It currently doesn't display any error on invalid email address.

**To Reproduce**
1. Go to the form that contains the email field.
2. Enter an invalid email (e.g., "abc" without an @ symbol).
3. Submit the form.
4. Instead of displaying the error, it sticks to the same section without information.

**Expected behavior**
It should display a proper error message incase of invalid email.

**Screenshots**
![image](https://github.com/user-attachments/assets/b491717a-3af4-43f9-a8fc-38f0a69e98bd)

**Comment by itsharshitrwt** [comment]
Can i work on this issue ?? plz assign

**Comment by bj-jiwrajka** [comment]
> @VesperAkshay Can i work on this issue ?? plz assign

In open source, when an issue is assigned to someone, you're not to work on it or ask for it to be reassigned. Follow the rules. And next time, read the guidelines before jumping in.

**Comment by itsharshitrwt** [comment]
Hi , @bj-jiwrajka , My apologies ,  I will surely take care of that next time , Are you working on this issue?

**Comment by bj-jiwrajka** [comment]
> Hi , @bj-jiwrajka , My apologies , I will surely take care of that next time , Are you working on this issue?

yes, I am
