### ISSUE TITLE
[Build]: Fix Blank User Profile Picture and Set Default Image

### ISSUE THREAD

**Issue by shubhagarwal1** [VesperAkshay/qr-code-generator#139]
Resolve the issue where a blank or missing image is shown for the user profile picture. Implement logic to check if the user's profile picture is unavailable or invalid, and display a default image instead. 
Hey @VesperAkshay please assign this task to me 
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/5e587204-e291-442d-9fb1-f8eee14ddd21">

**Comment by shubhagarwal1** [comment]
> Can't open multiple issue @shubhagarwal1
Can work on this if i made in time?

**Comment by VesperAkshay** [comment]
Yes first complete the first issue then you can work on this

**Comment by Cleveridiot07** [comment]
Hey @VesperAkshay, I’d like to request to be assigned this issue.

**Comment by VesperAkshay** [comment]
@shubhagarwal1  Due to inactivity i am assigning this issue to @Cleveridiot07

**Comment by Cleveridiot07** [comment]
Thanks for assigning, @shubhagarwal1! I'm working on the issue now
