### ISSUE TITLE
[Docs]: Add Steps for Firebase Authentication Keys Configuration to README and repository stats like stars, prs, visits, 

### ISSUE THREAD

**Issue by nidhi2026** [VesperAkshay/qr-code-generator#141]
**Current Section**
 The current README does not contain any detailed instructions for Firebase Authentication setup or a project overview. There is no section on how to configure Firebase keys, nor any contributor information in the contributing section. Also, the repo doesn't have GitHub repository stats.

**Proposed Change**
1. Add a detailed step-by-step guide for setting up Firebase Authentication, including creating a Firebase project, enabling Firebase Authentication, generating API keys, and configuring environment variables, to assist first-time contributors.
3. Expand the contributing section to include a list of contributors to the project.
4. Add GitHub repository stats in readme

**Rationale**
new developers can easily configure Firebase without unnecessary confusion. This will lower first-time contributors' barriers, making the onboarding process smoother, while a contributor list will help recognize the efforts of those who have contributed to the project and foster a collaborative environment.

**Additional Information**
Final looks of new readme
![image](https://github.com/user-attachments/assets/af48ea9d-2ade-4384-a218-1ac71be06c04)
![image](https://github.com/user-attachments/assets/714970cd-0a4a-4f11-bb1e-755a169d1a85)
![image](https://github.com/user-attachments/assets/e60caf0b-b3dd-475d-acd6-4d9fae066738)
![image](https://github.com/user-attachments/assets/ca9f7fc8-40d8-4241-b2f2-38f65340fa2c)
![image](https://github.com/user-attachments/assets/a213f6d2-695d-4923-b7b9-0e18fa684240)
![image](https://github.com/user-attachments/assets/7207d0e9-7706-44ae-ba64-09a16c799f2d)
![image](https://github.com/user-attachments/assets/19148da1-279c-4953-a112-255dc0318f4c)

**Comment by nidhi2026** [comment]
@VesperAkshay 
If this looks fine, please assign this to me

**Comment by VesperAkshay** [comment]
@nidhi2026 Assigned you the issue

**Comment by nidhi2026** [comment]
@VesperAkshay 
I have made the pr for this, kindly check.
