### ISSUE TITLE
[Bug]: Fix Black Text in Social Media QR Code Generator on Dark Mode & Enhance with Styled Popups for Social Media Links

### ISSUE THREAD

**Issue by nidhi2026** [VesperAkshay/qr-code-generator#142]
**Description**

**To Reproduce**
1. Go to `Generate social media Qr code`
2. Write text in dark mode
3. The text appears black, not visible properly.

**Expected behavior**
Text to be whitish in dark mode to be visible.

**Screenshots**
In dark mode, the text color for social media platform names in the QR code generator appears black, making it difficult to read against the dark background.
![image](https://github.com/user-attachments/assets/ca0dc434-1ad3-4162-991f-0a4e1de832f8)

**Suggestions**
1. Light text for dark mode
2. Styled pop-ups when we hover over the social media platforms

Improved code changes
![image](https://github.com/user-attachments/assets/fddbed34-744e-43dc-821d-eaa64ecc3a78)

**Environment:**
 - OS: Windows
 - Browser chrome
 - Version 129.0.6668.90

**Additional context**

**Comment by nidhi2026** [comment]
@VesperAkshay 
Please assign this bug to me. Are pop-ups good to be included, or should I just address the text visibility issue?

**Comment by VesperAkshay** [comment]
@nidhi2026 Can't open multiple issues

**Comment by nidhi2026** [comment]
@VesperAkshay , the previous issue has been merged, can I start working on this now. Can you please assign the labels gssoc-ext and level

**Comment by VesperAkshay** [comment]
@nidhi2026 assigned the issue

**Comment by nidhi2026** [comment]
@VesperAkshay 
can more social handles be added like TikTok and Snapchat
this is what it looks like
![image](https://github.com/user-attachments/assets/e955c27d-c142-478c-8859-80a93e920a11)
or keep it same as before
