### ISSUE TITLE
Title page is wrong

### ISSUE THREAD

**Issue by Risheendra183** [VesperAkshay/qr-code-generator#15]
The title page is wrong i will correct it plz assign me and label under GSSOC 24 ext 
![Screenshot 2024-10-01 224623](https://github.com/user-attachments/assets/e8f5213d-f763-42ce-b108-628bb8731cd2)

**Comment by chmp0940** [comment]
pls assign it to me i will do it 1

**Comment by subin-shk** [comment]
hello assign this to me. im beginner and idk what else to do

**Comment by VesperAkshay** [comment]
I am closing this issue as it has already been resolved
