### ISSUE TITLE
[Bug]: Sign-up/Login page is not responsive, "Already a member" link not visible on mobile view

### ISSUE THREAD

**Issue by Amulya-Codes** [VesperAkshay/qr-code-generator#152]
**Description**

The sign-up/login page is currently not responsive on mobile devices. Specifically, the "Already a member?" link is not visible on smaller screen sizes such as phones, making it difficult for users to navigate to the login page.

**To Reproduce**
1. Go to the sign-up/login page on a mobile device (or resize browser window to a mobile screen size).
2.Attempt to locate the "Already a member?" link.

**Expected behavior**

The "Already a member?" link should be visible and accessible on all screen sizes, including mobile devices.

**Screenshots**
![image](https://github.com/user-attachments/assets/3a6af807-bffd-4c58-944e-8559d676df5d)

**Comment by VesperAkshay** [comment]
@Amulya-Codes Assigned

**Comment by Shalinis19137** [comment]
I really like your website and want to contribute can you assign me this issue under gssoc-ext2024

**Comment by VesperAkshay** [comment]
Issue has been solved
