### ISSUE TITLE
Help button: For directly scrolling down 

### ISSUE THREAD

**Issue by banasmita24** [VesperAkshay/qr-code-generator#153]
Problem Statement
Currently, users have to manually scroll through the page to know how to use, which can be cumbersome.

Proposed Solution
Implement a "Help" button that, when clicked, will automatically scroll the page down to "How do I create a free QR Code"
The button could be fixed to the corner of the page.
Smooth scrolling animation could be applied when the button is clicked.

I would like to address this. please assign this to me under gssoc-ext and hactoberfest-accepted
Thank you:)

**Comment by VesperAkshay** [comment]
@banasmita24 Assigned

**Comment by vijaychandra1910** [comment]
Please it to me I want to work on it. @VesperAkshay

**Comment by banasmita24** [comment]
@VesperAkshay Thank you. Will work on it.
