### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Rx-Metallica** [VesperAkshay/qr-code-generator#16]
Contributing Guideline

**Comment by Rx-Metallica** [comment]
> Contributing Guideline

I would like to work on this

**Comment by VesperAkshay** [comment]
Issue has been assigned

**Comment by Rx-Metallica** [comment]
> Issue has been assigned
> 

Can u pls assign label of hactoberfest and  gssoc

**Comment by Rx-Metallica** [comment]
> Issue has been assigned
> 
Before merging
Pls check the label of hacktoberfest-accepted there's a spelling mistake in it.
