### ISSUE TITLE
[Feature]: Strong password recommendation

### ISSUE THREAD

**Issue by Ishika-Gupta06** [VesperAkshay/qr-code-generator#170]
Asking user to create a strong password to enhance account security 
adds better UX
![Screenshot 2024-10-10 121712](https://github.com/user-attachments/assets/8f872dba-4416-4b63-9b14-56532dd9bdd5)
![Screenshot 2024-10-10 121736](https://github.com/user-attachments/assets/fa4c8322-8ff6-40ed-9a59-139f8b53c632)

**Comment by VesperAkshay** [comment]
@Ishika-Gupta06 can't open multiple issue
