### ISSUE TITLE
[Bug]: Bad login and signup pages mobile view

### ISSUE THREAD

**Issue by PavanTeja2005** [VesperAkshay/qr-code-generator#177]
**Description**
Home page is fine in mobile view but login and signup pages are very bad in mobile browser.

**To Reproduce**
Open login page in mobile browser 

**Expected behavior**
i expected that the mobile view would be neat and nice.

**Screenshots**
![Screenshot_2024-10-11-09-11-59-990_com.android.chrome.jpg](https://github.com/user-attachments/assets/0a1d6c01-fdca-4e3f-9349-14f806cc7819)

**Environment:**
 - mobile browser 

**Additional context**

**Comment by VaibhavKatariya** [comment]
Hey @PavanTeja2005, this issue has been addressed in this PR
- #179

**Comment by PavanTeja2005** [comment]
Oh, that's great. I only searched for keywords related to "mobile".... My bad. I will close this issue.
Thanks for letting me know.
