### ISSUE TITLE
Theme Icon Affects Only Navbar Background, No Impact on Full Page (dashboard)

### ISSUE THREAD

**Issue by Vishv0407** [VesperAkshay/qr-code-generator#18]
**Description**: On the dashboard page, the theme icon currently only changes the background color of the navbar. The rest of the page is unaffected, leading to an inconsistent user experience. Ideally, the theme toggle should apply a color contrast change across the entire dashboard page, ensuring that both light and dark themes are fully reflected.

**Expected Behavior**: When the theme icon is toggled, the entire page should switch between dark and light themes. This includes changing the background, text colors, and any other UI elements to maintain proper color contrast.

**Next Steps:**

Update the color scheme to apply consistent color contrast for both dark and light themes across all components on the dashboard page. Ensure accessibility standards are followed for color contrast.

**Proposed Fix:** Work on enhancing the color contrast for both dark and light themes to ensure a smooth and consistent experience throughout the page.

Current Page screenshots:
![Screenshot 2024-10-01 232241](https://github.com/user-attachments/assets/67c5457e-cb2d-4d06-9516-cf45ecb26393)
![Screenshot 2024-10-01 232250](https://github.com/user-attachments/assets/43bda9a8-7766-432a-9347-84be51daf573)

**Comment by Vishv0407** [comment]
Please assign this issue to me, i want to work on this. 
I am a contributon of GSSOC'24 and Participated in Hackoberfest'24

**Comment by VesperAkshay** [comment]
The navbar is a separate component you have to add the nav bar in the main component and do all the changes

**Comment by Vishv0407** [comment]
@VesperAkshay Should i change currently colourful design to formal theme ??

![image](https://github.com/user-attachments/assets/d4f066f0-953e-4361-8fd0-486f5fbc5b72)

**Comment by Vishv0407** [comment]
We are currently changing the theme by updating states, but the preference resets to the default light theme upon refreshing the page. To persist the user's theme preference, we should store the selected theme (dark or light) in localStorage. This way, we can save the user's preference, and upon page reload, the website can check localStorage for the saved theme and apply it accordingly.

Also you can give your opinion on this dark theme.
![image](https://github.com/user-attachments/assets/072bf9c6-e9ef-4607-ac5b-b0bde881d446)

**Comment by VesperAkshay** [comment]
That's a good idea but we have firebase as backend if you want you can store there also if you want 
but local storege works as well !!

**Comment by Vishv0407** [comment]
@VesperAkshay Hello, I have opened a pull request, review it and make comment. (right now that request is falied due to vercel)
