### ISSUE TITLE
Register Button can be Fixed for smaller devices

### ISSUE THREAD

**Issue by Sameeratweb** [VesperAkshay/qr-code-generator#19]
![Screenshot 2024-10-01 232517](https://github.com/user-attachments/assets/050b020f-1b93-4e42-9d65-0ac391da659f)
Register button can be made responsive for smaller devices . and placed with proper structure, spacing and alignment.

I would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution. I can offer you a responsive and new look for the button .

**Comment by bj-jiwrajka** [comment]
> ![Screenshot 2024-10-01 232517](https://private-user-images.githubusercontent.com/115576990/372592663-050b020f-1b93-4e42-9d65-0ac391da659f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzAzNTQsIm5iZiI6MTcyODU3MDA1NCwicGF0aCI6Ii8xMTU1NzY5OTAvMzcyNTkyNjYzLTA1MGIwMjBmLTFiOTMtNGU0Mi05ZDY1LTBhYzM5MWRhNjU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNDIwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjQ5ZGMwZjc1YzAxZWRkY2M4ZWE0NzdkNDYwN2Y2YmEyM2E5MjE5MGMxOWEyY2IyYjU1M2NiNTFiN2JmNTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fAapmn-pI4uIynjD62TjDzBggfgZn9GlvMLWFuuvF2Y) Register button can be made responsive for smaller devices . and placed with proper structure, spacing and alignment.
> 
> I would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

are you working on it?
