### ISSUE TITLE
[Design]: Need to make this website responsive 

### ISSUE THREAD

**Issue by srivishnu2805** [VesperAkshay/qr-code-generator#199]
**Current Design**
The current design has no responsive in mobile and tablet view

**Proposed Design**
Need to add media Query and fix the responsive nature

**Mockups/Examples**
Include any mockups or examples.

**Benefits**
It helps to view on all devices without errors

**Additional Information**
![image](https://github.com/user-attachments/assets/6df9ffca-5bba-4066-be20-3652ce94b0d5)
if it is fixed the view will be enhanced

**Comment by avishek999** [comment]
assign me this task under  hackOctoberFest and GSSOC-Extd label under any Level
