### ISSUE TITLE
Bug: Avatar Image Not Loading in Header Component

### ISSUE THREAD

**Issue by hkcodings** [VesperAkshay/qr-code-generator#21]
![Screenshot (102)](https://github.com/user-attachments/assets/ea527fa5-38ac-47e9-911f-061b17a03969)

**Comment by hkcodings** [comment]
Please assign this issue to me under the GSSOC and Hacktoberfest labels.

**Comment by abishek1740P** [comment]
Assign me this issue under hacktoberfest2024 and GSSOC

**Comment by VesperAkshay** [comment]
I have checked it the profile is loading perfectly in various devices
