### ISSUE TITLE
[Feature]: ChatBot Design added to the website. 

### ISSUE THREAD

**Issue by mansiruhil13** [VesperAkshay/qr-code-generator#235]
![Screenshot 2024-10-18 015419](https://github.com/user-attachments/assets/ec8c1775-de0a-478d-b9ff-4f7e36ae7d90)
Added on Landing page of QR code website

**Comment by mansiruhil13** [comment]
can you assign this issue under gssoc and hacktoberfest??

**Comment by Pujan-sarkar** [comment]
@mansiruhil13  okay i am assigning you , best of luck.

**Comment by mansiruhil13** [comment]
> @mansiruhil13 okay i am assigning you , best of luck.

I have created pr #251 can you please review??

**Comment by Balamurugan-cyber** [comment]
please assign this issue
