### ISSUE TITLE
Request for [Type of Template] Template

### ISSUE THREAD

**Issue by shubhagarwal1** [VesperAkshay/qr-code-generator#24]
- I would like to request a [type of template, e.g., bug report, feature request] template for repository to streamline issue creation. This template will include predefined fields to ensure consistency and completeness in reports. Having a template will help contributors provide the necessary details upfront, making it easier to track, prioritize, and resolve issues efficiently. 
Hi @VesperAkshay please assign me with this task with labels (gssoc-ext, level)

- would look like this when someone will raise a issue 
![Screenshot 2024-10-02 at 1 57 41 AM](https://github.com/user-attachments/assets/4756425e-361c-44d5-97a2-e08383812713)

**Comment by samyak-aditya** [comment]
I think its already implemented

**Comment by VesperAkshay** [comment]
This is not implemented 
I also want you to add some more workflow for
when a pull request is merged 
when pull requested is created 
add a greeting message
