### ISSUE TITLE
Giving better color in background

### ISSUE THREAD

**Issue by SohamDas00** [VesperAkshay/qr-code-generator#28]
Instead of using white background color it can be different color which enhance the user experience 

![Screenshot 2024-10-02 103424](https://github.com/user-attachments/assets/47b629e4-738d-4d46-9410-ee14827f4a35)

**Comment by Subashree-selvaraj** [comment]
can you assign this issue to me under gssoc exd

**Comment by harish08102004** [comment]
Hey, it's been four days since this issue was created. If no one is currently working on it, I'd be happy to take it on.
