### ISSUE TITLE
Feature Request: Add "Activate Flash" Functionality

### ISSUE THREAD

**Issue by Isax03** [VesperAkshay/qr-code-generator#3]
A useful enhancement would be to add an "Activate Flash" feature to improve QR code scanning in low-light conditions.

Feature suggestion:
- Include a toggle button to turn the device's flashlight on or off during QR code scanning.

**Comment by Isax03** [comment]
I think I can not assign issues. And I am already working on that. There is a litte bug I have to fix then it is ready

**Comment by georgioupanayiotis** [comment]
ok no prob!

**Comment by SaanyaGarg5** [comment]
i can work on this issue

**Comment by Isax03** [comment]
Already done... Later I will submit the pull request
