### ISSUE TITLE
Improve README File with Detailed Project and Setup Information

### ISSUE THREAD

**Issue by chikatlarakesh** [VesperAkshay/qr-code-generator#30]
Hi @VesperAkshay ,

I would like to suggest an improvement for the README.md file to make the project more accessible for contributors and new users. The current README can be enhanced by including:

1.)Detailed project description highlighting features like QR Code customization (patterns, frames, colors, etc.) and Firebase authentication.
2.)Clear installation steps for cloning the repo, installing dependencies, and running the project locally.
3.)Explanation of the Firebase environment variables setup for proper authentication and storage configuration.
4.)Contribution guidelines and a contact section for better community engagement.
5.)The updated README would provide better clarity and ease of use for anyone looking to contribute or use the project.

Please let me know your thoughts on this! I’d be happy to assist further with this improvement.

**Comment by VesperAkshay** [comment]
issue has been assigned

**Comment by chikatlarakesh** [comment]
> issue has been assigned

I have made the changes and raised a pull request. Kindly spare some time reviewing it.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by VesperAkshay** [comment]
Its already done i forgot to close the issue
