### ISSUE TITLE
 Add "Scroll to Top" Button to the Website

### ISSUE THREAD

**Issue by Vishwajeet594** [VesperAkshay/qr-code-generator#36]
### Summary:
**We would like to implement a "Scroll to Top" button that allows users to quickly return to the top of the page with a single click, enhancing navigation, especially on longer pages.**

### Problem/Opportunity:

**1. On pages with significant content or long scrolling, users may find it difficult to return to the top manually.
2. Adding a "Scroll to Top" button will improve user experience and navigation efficiency.**

**Comment by meghanakn473** [comment]
hey @Vishwajeet594 please assign me this issue, i would like to work on it.

**Comment by VesperAkshay** [comment]
You can do one issue at a time

**Comment by meghanakn473** [comment]
Sure can u please assign me and mention the labels

**Comment by VesperAkshay** [comment]
@meghanakn473 after is it giving some error

**Comment by meghanakn473** [comment]
yeah it gave me this 

![Screenshot (139)](https://github.com/user-attachments/assets/0ce153e6-ce44-432c-98e0-abbd00cc9c83)

**Comment by VesperAkshay** [comment]
For this you have to add firebase api keys
I have given the .env template in readme 
create new project in firebase add you project add api key in .env file to run firebase

**Comment by meghanakn473** [comment]
> For this you have to add firebase api keys I have given the .env template in readme create new project in firebase add you project add api key in .env file to run firebase

well @VesperAkshay i hv tried to do this so many times but the project in firebase is not able to create succesfully

**Comment by VesperAkshay** [comment]
I can provide you with the test api keys so that you can run it in your local machine

**Comment by VesperAkshay** [comment]
Message me on discord I will provide you with the test api keys try that see if it works

**Comment by meghanakn473** [comment]
> Message me on discord I will provide you with the test api keys try that see if it works

@VesperAkshay check it out at discord

**Comment by VesperAkshay** [comment]
I haven't received any messages on discord give me your discord id will message you

**Comment by meghanakn473** [comment]
> I haven't received any messages on discord give me your discord id will message you

@VesperAkshay , knmeghana - id and display name is K N Meghana

**Comment by meghanakn473** [comment]
> I haven't received any messages on discord give me your discord id will message you

@VesperAkshay , knmeghana-id and display name as K N meghana

**Comment by Vishwajeet594** [comment]
sir please assign this issue to me bcz i raise this issue

**Comment by VesperAkshay** [comment]
@meghanakn473 You haven't accepted the request to assist you further i am assigning the issue to @Vishwajeet594

**Comment by meghanakn473** [comment]
Hey I had issues with my phone couldn't connect past 10hrs ....if there is any possibility to reassign me please do the needful @VesperAkshay 
Bcz I hv almost updated with codes and Feature...I hope you'll consider this

**Comment by VesperAkshay** [comment]
Has your error with the firebase resolved if so i am assigning it to you 
because you have implemented it

**Comment by meghanakn473** [comment]
> Has your error with the firebase resolved if so i am assigning it to you 
> because you have implemented it

I have accepted on discord...can u send the api keys so that I can check n run?

**Comment by VesperAkshay** [comment]
Okay

**Comment by meghanakn473** [comment]
hey its totally working..
hey @VesperAkshay shd i mention the api keys in .env file in my forked repo before making pr or not??

**Comment by meghanakn473** [comment]
Im grateful for the opportunity provided, also
@VesperAkshay can you please assign level 2/3 label

**Comment by VesperAkshay** [comment]
added the label

**Comment by meghanakn473** [comment]
thank you

**Comment by SumitSahu44** [comment]
hey @VesperAkshay assign this to me i will do it perfectly because i will do same work on recent pr so add label gssoc-ext and assign me

**Comment by meghanakn473** [comment]
> hey @VesperAkshay assign this to me i will do it perfectly because i will do same work on recent pr so add label gssoc-ext and assign me

its already and submitted and merged...
