### ISSUE TITLE
Implement Min Character Requirement for Feedback Submission

### ISSUE THREAD

**Issue by AdityaP700** [VesperAkshay/qr-code-generator#42]
![image](https://github.com/user-attachments/assets/8566f156-7934-436f-9dfc-77ccc9279737)
It has been observed that there is currently no **minimum** character limit for submitting feedback. To mitigate the potential for spam feedback submissions and ensure that users provide meaningful responses, it is recommended to implement a minimum character length requirement for feedback input.

**Comment by AdityaP700** [comment]
Hope you will look into this issue and hope i will be assigned to fix it . Thanks in anticipation

**Comment by AdityaP700** [comment]
Hello @VesperAkshay,
I hope this message finds you well. I would like to kindly request the addition of the label "GSSOC-extend" to my repository. This addition would be greatly appreciated as it will contribute to the overall count.
Thank you for your consideration.

**Comment by VesperAkshay** [comment]
Added the gssoc-ext label
