### ISSUE TITLE
"Add 'Follow Us on Social Media' Section"

### ISSUE THREAD

**Issue by AswaniBolisetti** [VesperAkshay/qr-code-generator#43]
Issue Description:
The website currently lacks a 'Follow Us on Social Media' section. I propose adding social media links (icons and handles) to encourage users to connect with us on platforms like Facebook, Twitter, Instagram, etc.

I’d like to work on adding this feature. Please assign this to me under gssoc24-ext, hacktoberfest-accepted

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by VesperAkshay** [comment]
Already been assigned

**Comment by bj-jiwrajka** [comment]
> Issue Description: The website currently lacks a 'Follow Us on Social Media' section. I propose adding social media links (icons and handles) to encourage users to connect with us on platforms like Facebook, Twitter, Instagram, etc.
> 
> I’d like to work on adding this feature. Please assign this to me under gssoc24-ext, hacktoberfest-accepted

there is already a section for this. I think this issue is irrelevant
![image](https://github.com/user-attachments/assets/4b4631a2-7eb0-4bf5-876a-31f0feeec4c9)
