### ISSUE TITLE
Logout button is not working on dashboard page

### ISSUE THREAD

**Issue by Vishv0407** [VesperAkshay/qr-code-generator#47]
On dashboard page, when click on Logout button it will redirect to /logout and it is currently empty. We can do two thing one is remove that logout button or other is add a confirmation alert and then user can logout. 

This confirmation thing is also done at that dropdown Logout option, when click on logout it directly redirect to home page instead of that we can ask for confirmation then redirect. 

So which option is prefereable for this issue ?

**Comment by VesperAkshay** [comment]
The confirmation option is good

**Comment by varunvaatsalya** [comment]
@VesperAkshay  I have fixed the problem of the dashboard logout button and along with that I have made other bugs and corrections and have also created a pull request. Please review it.

**Comment by VesperAkshay** [comment]
@varunvaatsalya I have checked and given correction what you have to do

**Comment by Vishv0407** [comment]
Should i continue with this or not ?

if not then please assign this issue to @varunvaatsalya, it will helpful for him.

**Comment by VesperAkshay** [comment]
@Vishv0407 you can work on the issue as the confirmation thing is still there to implement

**Comment by Vishv0407** [comment]
Okay @VesperAkshay will do it by tonight.

**Comment by VesperAkshay** [comment]
Okay
