### ISSUE TITLE
converting create react app to vite 

### ISSUE THREAD

**Issue by Ajdecoder** [VesperAkshay/qr-code-generator#48]
converting cra to vite to enhance development experience to increase versatility of the website development across developers and enhance development speed by 65%

**Comment by VesperAkshay** [comment]
can you convert it to nextJs

**Comment by Ajdecoder** [comment]
yup it would be even better but some consideration measures you have to take as you would have to make migerations over deployements on vercel you have priorly did can i proceed?

**Comment by VesperAkshay** [comment]
there is a test branch You can push that migrated code to that branch instead of main 
by this we can test how it works and then we can merge it to main and then deploy it 

Is this okay with you
