### ISSUE TITLE
Enhance the website 

### ISSUE THREAD

**Issue by RIYA-YADAV-19** [VesperAkshay/qr-code-generator#49]
Enhance the website to make it more interactive and modern so that user can find it more interesting to use this.

**Comment by RIYA-YADAV-19** [comment]
> 👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!

Okay,sure

**Comment by VesperAkshay** [comment]
Can you provide details about the changes you are going to implement

**Comment by RIYA-YADAV-19** [comment]
> Can you provide details about the changes you are going to implement

To improve the user interface, I will enhance the navigation bar to make it more dynamic and smooth, especially when clicked, as the current one feels a bit static and awkward. Additionally, I will refine the design and functionality of the home page by smoothing the animation.

**Comment by VesperAkshay** [comment]
I want to add one thing make it look minimalistic don't add to much colors

**Comment by RIYA-YADAV-19** [comment]
> I want to add one thing make it look minimalistic don't add to much colors

Okay I will , I want to make it more smooth with the animation.and also I will not use many colours to it

**Comment by VesperAkshay** [comment]
Okay

**Comment by RIYA-YADAV-19** [comment]
> Okay

So can I work with it ?

**Comment by VesperAkshay** [comment]
Yes you can

**Comment by RIYA-YADAV-19** [comment]
> Yes you can

Thank you, Will do it

**Comment by Bhavya445** [comment]
can u plss assign this to me

**Comment by VesperAkshay** [comment]
@Bhavya445 You can work on some other issue this one is already been assigned
