### ISSUE TITLE
Changing of the UI 

### ISSUE THREAD

**Issue by VesperAkshay** [VesperAkshay/qr-code-generator#5]
##Update

Change the UI to very minimalistic look it should not have very tacky and very bright colors

##Inspiration
You can take inspiration from this 

![Screenshot (120)](https://github.com/user-attachments/assets/094dcad0-ad1e-4afc-b061-3c4b88561bd3)
![Screenshot (121)](https://github.com/user-attachments/assets/bd2a6df7-a6f1-4ee3-b8e0-dfacf23031ce)
![Screenshot (122)](https://github.com/user-attachments/assets/5afc93ec-cf65-4b19-83b8-14ea9f203a61)

**Comment by SaanyaGarg5** [comment]
i want to contribute to this...

**Comment by tarunkumar2005** [comment]
I would like to contribute to this. I am from gssoc 2024 extended so assign it to me.

**Comment by priyaahm** [comment]
I'm a freelance UI/UX designer as well, I've created a lot of webpage mockups. So please assign this to me, I can work on this. 

Can you add gsoc extd and level labels

**Comment by Laikokwui** [comment]
@VesperAkshay @priyaahm is it ok to split some frontend part for me to handle? i'm also willing to help out.

**Comment by Amarjha01** [comment]
hi! Akshay I can change the UI  to very minimalistic look. I have a in-depth knowledge of **Tailwind CSS** which will align to your code base. This gonna be my first open source contribution so I'll give my best. Please assign me to solve this issue.

**Comment by VesperAkshay** [comment]
@Laikokwui @Amarjha01 If you want you both can split this issue and can work on this

**Comment by Amarjha01** [comment]
> @Laikokwui @Amarjha01 If you want you both can split this issue and can work on this

Yes sure sir just assign this to us we will connect on discord

**Comment by VesperAkshay** [comment]
Okay I am will assign this issue to both of you

**Comment by Amarjha01** [comment]
> Okay I am will assign this issue to both of you @Laikokwui @Amarjha01

okay sir we will start working on ASAP and will try to finish this by Saturday. 

@Laikokwui brother please join [Discord](https://discord.com/invite/GA7Ac377) & team up to solve this we will share work progress related information to avoid any conflict and smooth PR/MR .

**Comment by Amarjha01** [comment]
[qr-code-generator.pdf](https://github.com/user-attachments/files/17262226/qr-code-generator.pdf)



@VesperAkshay 
Hello sir,
After  analysing code and website I this home page is okay because that helps users to understand well how to use and why to choose this website to generate qr code.
The only UI needs to be changed is dashboard. So I designed a UI which will include all dashboard features as well as user can generate qr code in the same page and don't need to redirect to another page.

I'm requesting you to please check out the Design . We will start working on it once you approve design. Or you can give some suggestions like background color or position of any icon. 

@Laikokwui  you also check UI design brother

**Comment by VesperAkshay** [comment]
The initial design is quite satisfactory. However, I would like to request a couple of modifications:

Please change the font used in the design to enhance its overall appearance.
Additionally, I would appreciate it if you could make the section displaying the various QR options scrollable. This will ensure that any future additions can be easily accessed and reviewed.

**Comment by Amarjha01** [comment]
> The initial design is quite satisfactory. However, I would like to request a couple of modifications:
> 
> Please change the font used in the design to enhance its overall appearance. Additionally, I would appreciate it if you could make the section displaying the various QR options scrollable. This will ensure that any future additions can be easily accessed and reviewed.

Off course sir  I will modify font style , icon , optimize some space for QR code generation section  and  for "section displaying the various QR options scrollable"  
<img width="376" alt="image" src="https://github.com/user-attachments/assets/6e0e0317-98df-4b0d-8a56-e499e764a557">
this will be inside QR Code Generator section.

final selection design with some modification.
![selectedDesign](https://github.com/user-attachments/assets/788e8c5c-a5c3-4b91-b770-05b3075d7277)

**Comment by Amarjha01** [comment]
@Laikokwui Final design is here let's start working on it. 

![QR Code Generator](https://github.com/user-attachments/assets/2add9a3e-b18c-4b80-9775-221343a66639)

**Comment by VesperAkshay** [comment]
There is one suggestion don't push the code to main branch 
There is a old-version branch push this design to that 
First i want to test is then i will merge that to the main branch

**Comment by Amarjha01** [comment]
> There is one suggestion don't push the code to main branch There is a old-version branch push this design to that First i want to test is then i will merge that to the main branch

Okay sure sir.

**Comment by Amarjha01** [comment]
@VesperAkshay sir can you please change the level 3 to level3 because it didn't counted inleaderboard.

<img width="802" alt="image" src="https://github.com/user-attachments/assets/c7acf819-132d-44d6-bbb1-662cbdab90ef">

**Comment by VesperAkshay** [comment]
okay

**Comment by Amarjha01** [comment]
@VesperAkshay sir @Laikokwui is not available he has some family issue.

**Comment by Laikokwui** [comment]
@Amarjha01 not family issues, it's my own time management issues.

**Comment by Amarjha01** [comment]
https://github.com/user-attachments/assets/8d7d33e9-39a3-47f1-a6b8-90db4e6357a9

@VesperAkshay  Sir please verify the work before I raise PR.

**Comment by VesperAkshay** [comment]
Okay thats looks good 
and remember not to push in main branch
