### ISSUE TITLE
Enhancing readme.md

### ISSUE THREAD

**Issue by Aditijainnn** [VesperAkshay/qr-code-generator#51]
readme will look more good by adding drop down features and go to top toggle and pics
please assign me his issue under gssoc ext and hacktoberfest

**Comment by VesperAkshay** [comment]
This seams a great idea

**Comment by Bhavya445** [comment]
can u plss assign this to me

**Comment by Aditijainnn** [comment]
> This seams a great idea

@VesperAkshay you haven't gave me the points of it

**Comment by Aditijainnn** [comment]
> Added the level 2 label

Thank you
