### ISSUE TITLE
[FEATURE] Enhance the website to open links in new tab

### ISSUE THREAD

**Issue by Vaibhav-Kumar10** [VesperAkshay/qr-code-generator#56]
**Feature description:**
When clicking any link, it opens in the same tab. Updateing this will make it open in new tab.

**Use case:**
For the "Follow us on social" portion and sign in and register button, update the links to open in new tab.
This will make it comfortable for user to use the website more efficiently.

**Comment by Vaibhav-Kumar10** [comment]
Please assign me this issue as per hacktoberfest 2024

**Comment by bj-jiwrajka** [comment]
Hey @Vaibhav-Kumar10, are you working on it?

**Comment by Vaibhav-Kumar10** [comment]
Yes


But currently I am a little busy in some other cohorts.
Also my JS is not that good.
I need some time like till this weekend.
Otherwise you can assign it to any other person after that.
