### ISSUE TITLE
[FEATURE] contact us section

### ISSUE THREAD

**Issue by snehaapratap** [VesperAkshay/qr-code-generator#57]
Feature description:
Add a "Contact Us" section to the website. This section should include a form that allows users to send messages or inquiries directly from the QR code generation interface.

Use case:
Allows users to seek support, provide feedback, or make business inquiries directly from the QR code generator interface.
Enhances user engagement and improves service quality through direct communication.

Proposed solution:
Implement a responsive contact form at the bottom of the page or in a sliding sidebar.
Set up a backend endpoint to handle submissions, send auto-replies, and notify the support team.

![image](https://github.com/user-attachments/assets/0b9d3b5a-455f-4e53-a43c-0c0d5f133c85)

i want to add the contact us section below the follow us section.

**Comment by VesperAkshay** [comment]
There is already a support section in dashboard for contacting
