### ISSUE TITLE
[BUG] Adding transition on hovering 

### ISSUE THREAD

**Issue by Bhum-ika** [VesperAkshay/qr-code-generator#59]
**Description of the issue:**
When i am hovering on various containers, they are abruptly changing their color and getting bigger, rather it should be smooth

**Expected result:**
It should be smooth resulting in better UI
**Actual result:**
On hovering, there is an abrupt transformation taking place.

Kindly assign this issue to me under hactoberfest , gssocext and appropriate tags. I will start working on it.

**Comment by VesperAkshay** [comment]
Can you provide screen shot or video of the bug
