### ISSUE TITLE
Making the transition smooth when hovering over sections of the page for enhanced user experience.

### ISSUE THREAD

**Issue by Akshithanaverse** [VesperAkshay/qr-code-generator#60]
![Screenshot 2024-10-03 202041](https://github.com/user-attachments/assets/b45fa431-853a-427a-b13e-7e65867441f0)
->When hovered over the image the transition was not smooth

**Comment by VesperAkshay** [comment]
The labels have already been added

**Comment by Akshithanaverse** [comment]
I meant the labels need a correction from  "gssoc24-ext" to "gssoc-ext" and "hactoberfest-accepted" to "hacktoberfest-accepted".

**Comment by itsharshitrwt** [comment]
@VesperAkshay it seems that the issue is still not solved can i take up the issue ? plz assign

**Comment by VesperAkshay** [comment]
@Akshithanaverse what's the update on the issue

**Comment by Akshithanaverse** [comment]
The changes I was too make have already been done from someone else
