### ISSUE TITLE
Updating the Social Media Icons

### ISSUE THREAD

**Issue by nksmanya** [VesperAkshay/qr-code-generator#61]
The social media icons, in the "follow us on social" footer section, needs a bit of change. 
I would like to work on this. Please assign this issue to me.

Also label this issue.

**Comment by VesperAkshay** [comment]
What changes you want to add in that please elaborate

**Comment by nksmanya** [comment]
I would like to update all the social media icons in such a way that they all give off the same theme.

**Comment by VesperAkshay** [comment]
Okay

**Comment by nksmanya** [comment]
Can you please add the gssoc-ext and level labels to this issue please?
