### ISSUE TITLE
[BUG] Email verification is missing from the Sign-up page.

### ISSUE THREAD

**Issue by razputshivanshu** [VesperAkshay/qr-code-generator#65]
**Description of the issue:**
**Provide a clear and concise description of the issue.**

On the sign-up page, when a user registers with an email, there is no verification process in place to confirm whether the email belongs to the user. This allows users to provide incorrect email addresses, which could result in inaccurate data being stored on the server.

**Steps to reproduce:**
1. Navigate to the sign-up page.
2. Enter an email that doesn't belong to the user (or a random invalid email address).
3. Submit the form to complete the registration.

**Expected result:**
Describe what you expected to happen.
A verification email should be sent to the registered email address. The user should only be able to complete the sign-up process after verifying the email. This ensures that the email belongs to the user and is valid.

**Actual result:**
Describe what actually happened.
The user can register and log in without email verification. This allows incorrect or fake email addresses to be used, potentially leading to inaccurate data in the system.

**System information:**

- OS: Mac OS X
- Browser: Brave

**Additional information:**
- Any other information or context.
- There is no mechanism currently in place to prompt the user to verify their email after registration.
- Email verification should be implemented to ensure data accuracy and avoid the misuse of fake email addresses.

I would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd ,Hacktober and also assign the level tag for this issue.

**Comment by VesperAkshay** [comment]
The project is using firebase for email registration  will this be possible to do that without changing the setting inside firebase 
If yes
You can work on this issue that' really a great issue
