### ISSUE TITLE
[FEATURE] More font formatting styles and enable shortcuts 

### ISSUE THREAD

**Issue by mxyznk** [VesperAkshay/qr-code-generator#66]
edit: really sorry, added in the wrong repo.

pls delete this. sorry for the inconvenience caused

**Comment by VesperAkshay** [comment]
That's a good idea

**Comment by mxyznk** [comment]
@VesperAkshay i added the issue in the wrong repo. Pls delete this. Sorry...

**Comment by VesperAkshay** [comment]
No problem
