### ISSUE TITLE
THE REGISTER AND LOGIN FORM IS NOT INTERACTIVE AND EFFECTIVE FOR THE USERS

### ISSUE THREAD

**Issue by dnyanesh99borse** [VesperAkshay/qr-code-generator#67]
**Feature description:**
the current register and login form of the site is not interactive and effective. in sense the background of the forms 
then the fonts are quite poor ,
then there is no icons on the input side for more clearification,
then there is no title or the brief about the following proccess.

**Use case:**
this is neccessary cause, it will make the page more interactive and effective which will definitely led to increase the user experience on the side and will increase the spending time of the user on the page and will give the more clearification to the user about the respective process and will feel interactive and workable to the users. 

**Proposed solution:**
simply we have to update the login and register forms with some of the important updations. like improving the frontend is very important.
**Additional context:**
Any other relevant context or screenshots.
you can refer or assume as Before & After:

**BEFORE:**

![image](https://github.com/user-attachments/assets/6c2cc8e7-2299-4eb9-95c8-d1a41f30f3d6)

AFTER: 
![image](https://github.com/user-attachments/assets/5296d0ec-e7b6-4294-9478-3238a507756d)

**Comment by VesperAkshay** [comment]
Looks good to me

**Comment by JANVISAHARAN** [comment]
Can i also work on this issue

**Comment by rv-amberh** [comment]
PR is open here: https://github.com/VesperAkshay/qr-code-generator/pull/119 - Thanks!
