### ISSUE TITLE
Incorrect Google Icon Color & Button Background on Login Page

### ISSUE THREAD

**Issue by iAmDiksha** [VesperAkshay/qr-code-generator#8]
- **Google Icon Color**: The "Sign in with Google" button currently displays the Google icon in white, whereas it should use the **official multi-color Google logo** for consistency and recognition.

- **Button Background Color**: The background color of the "Sign in with Google" button is currently red, which is not visually appealing and does not align with Google's branding guidelines.

<img width="339" alt="image" src="https://github.com/user-attachments/assets/a804286b-669e-4219-9f0a-84bc14d735c1">

Could you please assign this issue to me under GSSOC'24 extd and hacktoberfest'24 ?

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution.

**Comment by VesperAkshay** [comment]
Why you unassigned the issue ?

**Comment by iAmDiksha** [comment]
Because I was unable to start this repo in my local PC. After cloning this repo.. I was trying npm install.. But even after so many trials, it is giving too much errors.. Couldn't find any solution.. That's why I unassigned the issue.

**Comment by varunvaatsalya** [comment]
@VesperAkshay I've solved this issue & created a pull request. please review it.
