### ISSUE TITLE
Creating a Android / IOS app for this website

### ISSUE THREAD

**Issue by VesperAkshay** [VesperAkshay/qr-code-generator#81]
# Issue Description: Development of Android/iOS App for Website

## Overview
The goal of this issue is to outline the requirements and considerations for developing a mobile application for both Android and iOS platforms based on the existing website.

## Objectives
- Create a user-friendly mobile application that mirrors the functionality of the website.
- Ensure compatibility with the latest versions of Android and iOS.
- Implement responsive design principles to enhance user experience on mobile devices.

## Features
1. **User Authentication**
   - Allow users to sign up, log in, and manage their accounts.
   
2. **Content Accessibility**
   - Provide access to all website content, including articles, images, and videos.

3. **Push Notifications**
   - Implement push notifications for updates, news, and alerts.

4. **Offline Access**
   - Enable offline access to certain features and content.

5. **Search Functionality**
   - Include a search bar for easy navigation and content discovery.

6. **Feedback Mechanism**
   - Allow users to submit feedback and report issues directly through the app.

## Conclusion
Developing a mobile app for our website will enhance user engagement and accessibility. This issue outlines the necessary steps and considerations for a successful launch.

**Comment by ParasY1724** [comment]
I can create web-app which will be same as website and installed on Android /  IOS

**Comment by VesperAkshay** [comment]
Okay I will assign you this issue
