### ISSUE TITLE
I want to add a contribution,md file

### ISSUE THREAD

**Issue by souvikpramanikgit** [VesperAkshay/qr-code-generator#83]
**Section of documentation:**
![image](https://github.com/user-attachments/assets/97fd0193-51d5-4f17-a62c-785ea811de68)
I want to update this

**Description of the update:**
![image](https://github.com/user-attachments/assets/4b579c27-da2d-4896-83b7-35bec62f3946)
I want to do this

**Reason for update:**
Why does this update improve the documentation?
This is really hard to see how to contribute. So my upgradation format wil help new open source learners.

**Comment by VesperAkshay** [comment]
Okay I will assign you the issue

**Comment by souvikpramanikgit** [comment]
Why did you close it @VesperAkshay
