### ISSUE TITLE
Adding Content

### ISSUE THREAD

**Issue by shreyad2806** [VesperAkshay/qr-code-generator#9]
Nothing is showing while clicking on tell me more. I can add content in tell me more . Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest. 
![WhatsApp Image 2024-10-01 at 18 34 45_a8168323](https://github.com/user-attachments/assets/00dd4fc9-7696-4df2-8a85-67411d1a347a)

**Comment by Shalinis19137** [comment]
I really like your website and want to contribute can you assign me this issue under gssoc-ext2024

**Comment by VesperAkshay** [comment]
@Shalinis19137 This issue has been completed
