### ISSUE TITLE
[DOCS] Creation of dedicated Contributing.md file & Updation of README.md(Design)

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [VesperAkshay/qr-code-generator#95]
**Contribution.md & README.md:**
![image](https://github.com/user-attachments/assets/ee9eae70-aad2-4eb7-8884-f91c855340e2)

**Description of the update:**
Currently, there is no dedicated file for contributors, such as a **Contributing.md**. Instead, the documentation for both the project and contributors is combined within the **README.md** file, which demonstrates poor documentation practices.

I intend to create a separate **Contributing.md** file so that contributors can review the contribution procedure in detail. I also plan to support new contributors by including some git commands and outlining the structure they should follow to contribute effectively to the repository.

Additionally, I want to revise the existing **README.md** file to make it more interactive and engaging.

**Reason for update:**
I believe that keeping the **README.md** focused on the project description will enhance the overall quality of the documentation. Making the **README.md** more intriguing will also increase user engagement and activity.

**Additional notes:**
N/A.

**Comment by Arpit529Srivastava** [comment]
@rajdeepchakraborty-rc can you please assign the issue to me under the label ```hactoberfest```

**Comment by rajdeepchakraborty-rc** [comment]
@VesperAkshay I want to ask whether I should name the project **QR Code Generator** or **QR Code Customization** in the **Contributor.md**. The **README.md** file says one but the repository name has "generator".

**Comment by rajdeepchakraborty-rc** [comment]
@Arpit529Srivastava Try finding and posting another issue under the repository and work on it after getting assigned to it.

**Comment by rajdeepchakraborty-rc** [comment]
@VesperAkshay, I am thinking of adding a Team section.
![image](https://github.com/user-attachments/assets/420fd751-ff86-479b-ad7f-d19c799883c8)
Should I keep the Contact and Team sections or merge them?

**Comment by VesperAkshay** [comment]
keep contact and teem seprated

**Comment by rajdeepchakraborty-rc** [comment]
Ok going with the current changes then.

**Comment by rajdeepchakraborty-rc** [comment]
@VesperAkshay  Please let me know whether I should name the project(in **README.md** and **Contributing.md**):
**QR Code Generator** or **QR Code Customization**
The README.md file says **QR Code Customization**, but the repository name has **QR Code Generator**.

**Comment by VesperAkshay** [comment]
Make it QR code generator

**Comment by rajdeepchakraborty-rc** [comment]
![image](https://github.com/user-attachments/assets/2f43209c-cb2c-4f48-b396-0b356bdc07c4)

@VesperAkshay I just wanted to inform you that the LinkedIn profile linked to your GitHub Profile is invalid. Please do update it at your earliest. I looked up your profile in the Mentors list.
![image](https://github.com/user-attachments/assets/4c3ed811-5216-4ba6-a685-9160da4b748b)

**Comment by VesperAkshay** [comment]
Okay thanks for telling i will update it
