### ISSUE TITLE
[FEATURE] Add Responsiveness

### ISSUE THREAD

**Issue by Karan-purkait** [VesperAkshay/qr-code-generator#97]
Description:
This page currently lacks responsiveness, making the UI inconsistent across different devices and screen sizes. To ensure a seamless user experience, we need to add responsiveness so that the [page/component] adapts well on various devices like mobile phones, tablets, and desktops.
Tasks:
1.Media Queries: Implement CSS media queries to adjust layouts for different screen sizes (mobile, tablet, desktop).
2. Fluid Layouts:  Modify or add fluid grids and flexible containers using frameworks like Bootstrap or Tailwind CSS to ensure responsiveness.
3. Responsive Images: Ensure images scale correctly based on screen size.
4. Testing: Test the responsiveness on different screen resolutions to verify UI consistency.
  
Expected Outcome:  
A fully responsive [page/component] that works seamlessly across all devices, ensuring an improved user experience.

Tech Stack:  
- CSS3 (with media queries)
- Bootstrap or Tailwind CSS (if using a CSS framework)
- JavaScript (for any dynamic resizing if required)

**Comment by Akanshaku** [comment]
pls assign me this issue @Pujan-sarkar

**Comment by Pujan-sarkar** [comment]
@Akanshaku this issue is already assigned, please go for another.

**Comment by Pujan-sarkar** [comment]
@Karan-purkait what's update ?

**Comment by Osank31** [comment]
please assing me this issue @Pujan-sarkar

**Comment by Codersweta7** [comment]
@Pujan-sarkar 
It is about 2 weeks , if the work is not done please assign that to me .

**Comment by Pujan-sarkar** [comment]
@Codersweta7 okay i am assigning you , try to complete this fast.

**Comment by Codersweta7** [comment]
I need time till 24 th Oct  ....

**Comment by Codersweta7** [comment]
@VesperAkshay 
I am not able to do , I have only knowledge of html , css and javascript ...little I know about backend .

**Comment by Pujan-sarkar** [comment]
Okay

**Comment by Pujan-sarkar** [comment]
@Codersweta7 you are unassigned

**Comment by BhavikaPachauri** [comment]
if this issue is open can i work on it

**Comment by Akanshaku** [comment]
if its not yet completed could you please assign me this @Pujan-sarkar

**Comment by Pujan-sarkar** [comment]
This issue has been solved by #245
