### ISSUE TITLE
Logged-in User Can Still Create a New Account – Security Vulnerability

### ISSUE THREAD

**Issue by VaibhavKatariya** [VesperAkshay/qr-code-generator#99]
**Description:**
I noticed a potential security vulnerability where a logged-in user is allowed to create a new account instead of being redirected to the dashboard. This could lead to confusion and possible misuse of authentication states. To ensure security and a smooth user experience, the app should prevent authenticated users from accessing the sign-up page and instead direct them to the dashboard.

![image](https://github.com/user-attachments/assets/2e82ef7b-c8b8-48fa-9690-2e72fffec60c)

**Steps to Reproduce:**
1. Log in to the application.
2. Navigate to the login/register page while still logged in.
3. Notice that the user can create a new account despite being authenticated.

**Expected Behavior:**
Once a user is logged in, they should be redirected to the dashboard, and access to the sign-up page should be restricted.

**Proposed Fix:**
Implement a check that verifies if a user is logged in and redirects them to the dashboard if they attempt to access the sign-up page.

**Additional Information:**
- This issue could potentially lead to duplicate accounts or misuse of the login state.
- I would like to work on this issue as part of Hacktoberfest and GSSoC-Ext. It would be great if you could add the `hacktoberfest`, `hacktoberfest-accepted` and `gssoc-ext`, `level 2` labels to it.

@VesperAkshay Please assign this issue to me.

Thank you!

**Comment by VesperAkshay** [comment]
Thankyou @VaibhavKatariya for pointing out this bug
